### ISSUE TITLE
More papers on bridge matching!

### ISSUE THREAD

**Issue by harryjo97** [dongzhuoyao/awesome-flow-matching#2]
Hi Tao,

Thank you for making a comprehensive list of literature on Flow matching!

- I'd like to recommend two works related to bridge matching:

**Diffusion Bridge Mixture Transports, Schrödinger Bridge Problems and Generative Modeling**
*Stefano Peluchetti*
Arxiv  2023 [[Paper]](http://arxiv.org/abs/2304.00917)
3 Apr 2023

**Learning Diffusion Bridges on Constrained Domains**
*Liu et al.*
ICLR 2024 [[Paper]](https://openreview.net/forum?id=WH1yCa0TbB)

- Also, two of my papers study bridge matching, which are accepted to ICML 2024. I'd appreciate it if you could add these to the list (maybe in the Application)!

**Generative Modeling on Manifolds Through Mixture of Riemannian Diffusion Processes**
*Jaehyeong Jo, Sung Ju Hwang*
ICML 2024 [[Paper]](https://arxiv.org/abs/2310.07216)
11 Oct 2023

**Graph Generation with Diffusion Mixture**
*Jaehyeong Jo, Dongki Kim, Sung Ju Hwang*
ICML 2024 [[Paper]](https://arxiv.org/abs/2302.03596)
7 Feb 2023

**Comment by phantimy** [comment]
Thank you for those suggestions, we have added them ^^
